"""BoN actor evaluation against a published policy-TD SVF critic.

The SVF export carries only what inference needs: the online Q1/Q2 and the
category-specific projection, under their original ``q.*`` and ``projection.*``
state-dict keys. It is not a standalone image-to-Q model — scoring has to
reproduce the feature path PolicyTDSVF used during training:

    raw      = bc2.backbone(batch)                          # frozen, bfloat16
    features = bc2_head.vl_self_attention(bc2_head.vlln(raw['backbone_features']))
    pooled   = features.mean(1, keepdim=True).float()
    embedded = projection(pooled, embodiment_id).float().tanh()
    q1, q2   = q(embedded, state * state_mask, action * action_mask)
    score    = min(q1, q2)

So three things must line up, and all three come from the checkpoint the SVF run
started from, not from the tuned actor:

- the frozen backbone and the reference head's VLLN / VL self-attention,
- the projection and Q weights from the export,
- normalization, taken from the same checkpoint's experiment_cfg/metadata.json,
  which is exactly what train_policy_td_svf.py hands ChunkEpisodeStream.

Candidates are generated by the tuned SVF actor. Selection is the highest
min(Q1, Q2). Nothing here needs training.pt, the optimizer, the EMA targets or
the soft-value head.
"""
import copy
import json
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import torch
from gr00t.model.svf.precision import q_forward_fp32, projection_forward_fp32
import torch.nn.functional as F
from safetensors.torch import load_file

from gr00t.data.schema import DatasetMetadata
from gr00t.data.transform.concat import ConcatTransform
from gr00t.data.transform.state_action import StateActionToTensor, StateActionTransform
from gr00t.model.checkpoint_bon_policy import repeat_batch, select_candidates
from gr00t.model.policy import (
    COMPUTE_DTYPE,
    Gr00tPolicy,
    squeeze_dict_values,
    unsqueeze_dict_values,
)

ALGORITHM_PREFIX = "policy-TD SVF"


class SVFCriticScorer(torch.nn.Module):
    """Frozen BC2 feature path plus the exported projection and double Q."""

    def __init__(self, reference_actor_path, horizon=16, device="cuda:0"):
        super().__init__()
        from gr00t.model.action_head.deas_critic import CategorySpecificMLP
        from gr00t.model.critic.networks import DoubleCritic
        from gr00t.model.gr00t_n1 import GR00T_N1_5

        actor = GR00T_N1_5.from_pretrained(
            str(reference_actor_path), torch_dtype=torch.bfloat16,
            tune_visual=False, tune_llm=False,
        )
        # PolicyTDSVF keeps the backbone frozen in bfloat16 and takes its
        # reference head as a deepcopy of the same checkpoint's action head.
        self.backbone = actor.backbone.requires_grad_(False).eval()
        self.vlln = actor.action_head.vlln.requires_grad_(False).eval()
        self.vl_self_attention = actor.action_head.vl_self_attention.requires_grad_(False).eval()
        width = actor.action_head.config.backbone_embedding_dim
        self.state_dim = actor.action_head.config.max_state_dim
        self.action_dim = actor.action_dim
        self.horizon = horizon
        del actor

        self.projection = CategorySpecificMLP(32, width, 1024, 64)
        self.q = DoubleCritic(64 + self.state_dim + horizon * self.action_dim, [512] * 4, output_dim=1)
        self.to(device).eval().requires_grad_(False)

    def load_export(self, path):
        weights = load_file(str(path))
        projection = {k[len("projection."):]: v for k, v in weights.items() if k.startswith("projection.")}
        q = {k[len("q."):]: v for k, v in weights.items() if k.startswith("q.")}
        unexpected = [k for k in weights if not k.startswith(("projection.", "q."))]
        if unexpected:
            raise ValueError(f"Unexpected keys in the SVF export: {sorted(unexpected)[:5]}")
        self.projection.load_state_dict(projection, strict=True)
        self.q.load_state_dict(q, strict=True)
        return len(projection), len(q)

    @torch.no_grad()
    def encode(self, backbone_input, prefix="eagle_"):
        with torch.autocast("cuda", dtype=torch.bfloat16):
            raw = self.backbone(backbone_input, eagle_prefix=prefix)
            features = self.vl_self_attention(self.vlln(raw["backbone_features"]))
            return features.float().mean(dim=1, keepdim=True)

    @torch.no_grad()
    def project(self, pooled, embodiment_id):
        return projection_forward_fp32(self.projection, pooled, embodiment_id)

    @torch.no_grad()
    def score(self, embedded, states, actions):
        q1, q2 = q_forward_fp32(self.q, embedded, states, actions)
        return torch.minimum(q1.float(), q2.float())


class CheckpointSVFBoNPolicy:
    """Sample from the SVF actor, rank the candidates by the SVF critic."""

    def __init__(self, actor_model_path, critic_model_path, embodiment_tag,
                 modality_config, modality_transform, denoising_steps=4,
                 num_samples=10, temperature=0.0, device="cuda:0",
                 reference_actor_path=None):
        if num_samples < 1 or temperature < 0:
            raise ValueError("Invalid BoN settings")
        critic_path = Path(critic_model_path)
        config = json.loads((critic_path / "config.json").read_text())
        algorithm = config.get("algorithm", "")
        if not algorithm.startswith(ALGORITHM_PREFIX):
            raise ValueError(f"Not a policy-TD SVF critic export: {algorithm!r}")
        horizon = config["horizon"]

        # The critic was trained on features from the run's starting checkpoint,
        # not from the actor the run produced, so it has to be named explicitly.
        if reference_actor_path is None:
            raise ValueError(
                "A policy-TD SVF critic scores features from the checkpoint its training "
                "started from. Pass --critic_reference_actor (the BC2 checkpoint)."
            )
        reference_actor_path = Path(reference_actor_path)

        self.critic = SVFCriticScorer(reference_actor_path, horizon=horizon, device=device)
        counts = self.critic.load_export(critic_path / "q_projection.safetensors")

        self.actor = Gr00tPolicy(actor_model_path, embodiment_tag, modality_config,
                                 modality_transform, denoising_steps, device)
        self.actor.model.requires_grad_(False)

        # Normalization follows the reference checkpoint, matching what
        # train_policy_td_svf.py passes to ChunkEpisodeStream.
        self.critic_transform = copy.deepcopy(modality_transform)
        metadata = json.loads((reference_actor_path / "experiment_cfg" / "metadata.json").read_text())
        tag = self.actor.embodiment_tag.value
        if tag not in metadata:
            raise ValueError(f"{reference_actor_path} has no metadata for embodiment {tag!r}")
        self.critic_transform.set_metadata(DatasetMetadata.model_validate(metadata[tag]))
        self.critic_transform.eval()

        self.critic_action_horizon = horizon
        self.action_dim = self.actor.model.action_dim
        if self.critic_action_horizon > self.actor.model.action_horizon:
            raise ValueError("Actor horizon too short for the critic")
        self.model = SimpleNamespace(critic_action_horizon=self.critic_action_horizon)
        self.device = torch.device(device)
        self.num_samples = num_samples
        self.temperature = temperature
        self.last_scores = None
        self.last_candidates = None
        print(f"policy-TD SVF BoN N={num_samples}; reference features from "
              f"{reference_actor_path}; loaded {counts[0]} projection and {counts[1]} Q tensors; "
              f"min(Q1,Q2)", flush=True)

    def get_modality_config(self):
        return self.actor.get_modality_config()

    def _normalize_candidates_for_critic(self, actions):
        data = {k: np.array(v, copy=True) for k, v in actions.items()}
        for transform in self.critic_transform.transforms:
            if isinstance(transform, (StateActionToTensor, StateActionTransform, ConcatTransform)):
                data = transform(data)
        action = torch.as_tensor(data["action"])
        if action.shape[-1] > self.action_dim:
            raise ValueError("Action width mismatch")
        return F.pad(action, (0, self.action_dim - action.shape[-1])).to(self.device, dtype=torch.float32)

    @torch.inference_mode()
    def get_action(self, observations):
        is_batch = self.actor._check_state_is_batched(observations)
        if not is_batch:
            observations = unsqueeze_dict_values(observations)
        observations = {k: np.asarray(v) for k, v in observations.items()}
        actor_input = self.actor.apply_transforms(dict(observations))
        critic_input = self.critic_transform(dict(observations))

        with torch.autocast(self.device.type, dtype=COMPUTE_DTYPE):
            backbone_input, action_input = self.actor.model.prepare_input(actor_input)
            raw = self.actor.model.backbone(backbone_input)
            batch = action_input["state"].shape[0]
            predicted = self.actor.model.action_head.get_action(
                repeat_batch(raw, self.num_samples),
                repeat_batch(action_input, self.num_samples),
            )["action_pred"]
        actions = self.actor._get_unnormalized_action(predicted.float())
        normalized = self._normalize_candidates_for_critic(actions)

        critic_backbone, critic_action = self.actor.model.prepare_input(critic_input)
        pooled = self.critic.encode(critic_backbone)
        embedded = self.critic.project(pooled, critic_action["embodiment_id"])
        state = critic_action["state"].float()
        if "state_mask" in critic_action:
            state = state * critic_action["state_mask"]
        scores = self.critic.score(
            embedded.repeat(self.num_samples, 1, 1),
            state.repeat(self.num_samples, 1, 1),
            normalized[:, : self.critic_action_horizon],
        )
        self.last_candidates = actions
        self.last_scores = scores.reshape(self.num_samples, batch).cpu()
        selected = select_candidates(actions, scores, self.num_samples, batch, self.temperature)
        if not all(np.isfinite(v).all() for v in selected.values()):
            raise ValueError("Nonfinite actions")
        return selected if is_batch else squeeze_dict_values(selected)
